base/urls.py
from django.urls import path
from . import views
from . import final_list_views

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('', views.home, name='home'),
    # path('dqa/', views.dqa, name='dqa'),
    path('import_data/', views.import_data, name='import_data'),
    path('error_check/', views.error_check, name='error_check'),
    path('final_list/', views.final_list, name='final_list'),
    path('final_list_report/', views.final_list_report, name='final_list_report'),
    path('reports/', views.reports, name='reports'),
    path('media_upload/', views.upload_media, name='media_upload'),
    path('upload_sample/', views.upload_sample_to_moda, name='upload_sample'),
    path('moda_user_mgt/', views.moda_user_mgt, name='moda_user_mgt'),
    path('import-csv/', views.CSVImportView.as_view(), name='csv_import'),
    path('import-tpm-csv/', views.TPMCSVImportView.as_view(), name='import_tpm_csv'),
    path('import-tpm-ee-csv/', views.TPMEEVImportView.as_view(), name='import_tpm_ee_csv'),
    path('drop_records/', views.CSVImportViewDropRecords.as_view(), name='drop_records'),
    
    path('sampling/', views.sampling, name='sampling'),
    path('est_sample/', views.CSVDataCountView.as_view(), name='est_sample'),
    path('generate_sample/', views.GenerateSampleView.as_view(), name='generate_sample'),
    path('approve_sample/', views.ApproveSampleView.as_view(), name='approve_sample'),
    path('sampling_report/', views.sampling_report, name='sampling_report'),
    path('sample_report/', views.SampleViewReport.as_view(), name='sample_report'),
    
    
    path('sampling_borderline/', views.sampling_borderline, name='sampling_borderline'),
    path('est_borderline_sample/', views.SampledLocations_bordeline.as_view(), name='est_borderline_sample'),
    # path('est_sample_borderline/', views.CSVDataCountViewBorderline.as_view(), name='est_sample_borderline'),
    path('gen_borderline_sample/', views.GenerateRandomSites.as_view(), name='gen_borderline_sample'),
    # path('approve_sample/', views.ApproveSampleView.as_view(), name='approve_sample'),
    
    path('custom_sampling_borderline/', views.custom_sampling_borderline, name='custom_sampling_borderline'),
    path('est_custom_borderline_sample/', views.SampledLocations_bordeline_custom.as_view(), name='est_custom_borderline_sample'),
    # path('est_sample_borderline/', views.CSVDataCountViewBorderline.as_view(), name='est_sample_borderline'),
    path('gen_custom_borderline_sample/', views.GenerateRandomSites_custom.as_view(), name='gen_custom_borderline_sample'),
    
    path('filal_list_locations/', views.SampledLocations.as_view(), name='filal_list_locations'),
    path('final_list_data_analysis/', views.FinalListDataAnalysis.as_view(), name='final_list_data_analysis'),
    path('final_list_data_analysis_report/', views.FinalListDataAnalysisReport.as_view(), name='final_list_data_analysis_report'),
    path('check_keys_in_excel/', views.check_keys_in_excel, name='check_keys_in_excel'),
    path('summary_view/', views.summary_view.as_view(), name='summary_view'),
    
    path('export/<str:model_name>/', views.export_model_to_excel, name='export_model_to_excel'),
    
    
    # test final views.
    path('final_list_test/', final_list_views.DataCountsGroupedView.as_view(), name='final_list_test'),
    # path('test_view_final_approval/', views.test_view_final_approval, name='final_list_test2'),
    path('test_view_final_approval/', views.FinalListApproval.as_view(), name='final_list_test3'),
    
    
    
]

data_quality/urls.py
from django.urls import path
from . import views

app_name = 'data_quality'  # replace 'data_quality' with your actual app name

urlpatterns = [
    path('', views.index, name='index'),
    path('create-df/', views.create_df, name='create-df'),
    path('import-data/', views.ImportDataView.as_view(), name='dqa'),
    path('dqa_analysis/', views.dqa_analysis, name='dqa_analysis'),
    path('excel_upload_view/', views.excel_upload_view, name='excel_import'),
    path('std_data_analysis/', views.std_data_analysis, name='analyze_data'),
    path('cfac_excel_upload_view/', views.cfac_excel_upload_view, name='cfac_excel_import'),
    path('cfac_village_list_prep/', views.process_excel_file, name='cfac_village_list_prep'),
    path('deduplicate_upload/', views.deduplicate_upload, name='deduplicate_upload'),
    path('deduplicate_export/', views.deduplicate_export, name='deduplicate_export'),
    path('compare_files/', views.compare_excel_documents, name='compare_files'),
    path('prepare_final_list/', views.prepare_final_list, name='prepare_final_list')
]

media_files/urls.py
from django.urls import path
from . import views

app_name = 'media_files'

urlpatterns = [
    path('', views.home, name='media_home'),
    path('upload_province/', views.uploadProvince, name='upload_province'),
    path('upload_district/', views.uploadDistrict, name='upload_district'),
    path('upload_tpm/', views.uploadTPM, name='upload_tpm'),
    path('upload_cp/', views.uploadCP, name='upload_cp'),
    path('upload_cfac/', views.uploadCFAC, name='upload_cfac'),
    path('upload_villages/', views.uploadVillages, name='upload_villages'),
    path('upload_sample/', views.uploadSampleToMoDa, name='upload_sample'),
    path('user_access/', views.update_user_access, name='user_access'),
]

targeting/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
    path('data_quality/', include('data_quality.urls')),
    path('media_files/', include('media_files.urls')),
    
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

base/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class UserRegisterForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']
    # styling the form
    

class UserLoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

    

base/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import AuthenticationForm
from django.contrib import messages
from .forms import UserRegisterForm, UserLoginForm
from django.contrib.auth.decorators import login_not_required
import io
import os
import time
from django.conf import settings
from django.core.files.storage import FileSystemStorage
from django.http import HttpResponse, JsonResponse
from .models import CPDataModel, TPMDataModel, TPMCSVData, CSVData, Sample, CPDataModel1, Sample1, TPM_SC_Data, TPM_EE_Data,FinalApproval, DroppedRecords # Adjust the models as needed

import pandas as pd
import numpy as np
from django.views import View
from django.http import HttpResponse
from django.core.files.storage import default_storage
from django.core.files.base import ContentFile
from django.db import transaction
import logging
from io import BytesIO
import pytz
from django.utils import timezone
from datetime import timedelta
from django.db.models import Count, Case, When, F, IntegerField, Sum, Subquery, OuterRef, Q, ExpressionWrapper, FloatField, Value,  CharField
from django.db.models.functions import Cast, Greatest, Coalesce
import random
import json
import datetime 
from django.forms.models import model_to_dict
import numpy as np


TOTAL_CLUSTERS = int(os.getenv('TOTAL_CLUSTERS'))
MAX_SAMPLE_SIZE = int(os.getenv('MAX_SAMPLE_SIZE'))
MIN_ACCEPTABLE_SAMPLE_SIZE_PERCENT = float(os.getenv('MIN_ACCEPTABLE_SAMPLE_SIZE'))
MAX_SAMPLE_SIZE_PER_CLUSTER = int(os.getenv('MAX_SAMPLE_SIZE_PER_CLUSTER'))
INCLUSION_ERROR_THRESHOLD = float(os.getenv('INCLUSION_ERROR_THRESHOLD'))
EXCLUSION_ERROR_THRESHOLD = float(os.getenv('EXCLUSION_ERROR_THRESHOLD'))
MIN_EXCLUSION_ERROR_RECORDS = int(os.getenv('MIN_EXCLUSION_ERROR_RECORDS'))

@login_not_required
def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Account created for {username}!')
            return redirect('login')
    else:
        form = UserRegisterForm()
    return render(request, 'register.html', {'form': form})

@login_not_required
def user_login(request):
    if request.method == 'POST':
        form = UserLoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('home')
            else:
                messages.error(request, 'Invalid username or password')
    else:
        form = UserLoginForm()
    return render(request, 'login.html', {'form': form})

def user_logout(request):
    logout(request)
    return redirect('login')

# Create your views here.
def home(request):
    return render(request, 'index.html')

def dqa(request):
    return render(request, 'temp.html', {'title': 'Data Quality Assessment'})

def import_data(request):
    if request.method == 'POST' and request.FILES['csv_file']:
        csv_file = request.FILES['csv_file']
        import_type = request.POST.get('import_type')        
        # Generate the new file name with timestamp
        file_name, file_extension = os.path.splitext(csv_file.name)
        timestamp = time.strftime("%Y%m%d-%H%M%S")
        new_file_name = f"{file_name}_{timestamp}{file_extension}"
        
        # Define the upload path
        upload_path = os.path.join('uploads', new_file_name)
        
        # Save the file to the 'uploads' folder
        fs = FileSystemStorage(location=os.path.join(settings.MEDIA_ROOT, 'uploads'))
        filename = fs.save(new_file_name, csv_file)
        
        # Optionally, save the file information to your model
        # Assuming you have a field `file_path` in your model to store the path
        # model_instance = CPDataModel(file_path=upload_path)
        # model_instance.save()

        return HttpResponse(f"File uploaded successfully: {filename}")
    
    return render(request, 'upload_csv.html')

def sampling(request):
    return render(request, 'sample_gen.html', {'title': 'Generate Sample'})

def sampling_report(request):
    return render(request, 'sample_report.html', {'title': 'Export Sample'})

def sampling_borderline(request):
    return render(request, 'sample_gen_borderline.html', {'title': 'Generate Borderline Sample'})

def custom_sampling_borderline(request):
    return render(request, 'custom_sample_gen_borderline.html', {'title': 'Generate Customized Borderline Sample'})

def error_check(request):
    return render(request, 'temp.html', {'title': 'Error Checking'})

def final_list(request):
    return render(request, 'final_list_gen1.html', {'title': 'Final List Generation'})

def final_list_report(request):
    return render(request, 'final_list_gen2.html', {'title': 'Final List Report'})

def reports(request):
    return render(request, 'temp.html', {'title': 'Reports'})

def upload_media(request):
    return render(request, 'moda_actions.html', {'title': 'MoDa Actions'})

def upload_sample_to_moda(request):
    return render(request, 'temp.html', {'title': 'Upload Sample to MODA'})

def moda_user_mgt(request):
    return render(request, 'temp.html', {'title': 'User Management'})



logger = logging.getLogger(__name__)

class CSVImportView(View):
    template_name = 'upload_csv.html'

    def get(self, request):
        return render(request, self.template_name)

    def post(self, request):
        # Check if this is supposed to be a PUT request
        if request.POST.get('_method') == 'PUT':
            return self._handle_file_upload(request, is_update=True, id_update=False, alternate=False)
        elif request.POST.get('_method') == 'ID_PUT':
            return self._handle_file_upload(request, is_update=True, id_update=True, alternate=False)
        elif request.POST.get('_method') == 'ALTERNATE_PUT':
            return self._handle_file_upload(request, is_update=True, id_update=True, alternate=True)
        else:
            return self._handle_file_upload(request, is_update=False, id_update=False, alternate=False)

    def _handle_file_upload(self, request, is_update, id_update=False, alternate=False):
        csv_file = request.FILES.get('csv_file')
        if not csv_file:
            messages.error(request, 'Please upload a CSV file.')
            return render(request, self.template_name)

        try:
            # Read CSV file
            df = pd.read_csv(csv_file)
            
            # Replace '/' with '_' in column names
            df.columns = df.columns.str.replace('-', '_')
            
            if 'ben_id' in df.columns:
                messages.error(request, 'Seems like wrong file is sent for process.')
                return render(request, self.template_name)
            
            # Process the DataFrame
            df, error_rows = self.process_dataframe(df, is_update, id_update, alternate)

            # Generate response CSV
            output = BytesIO()
            df.to_csv(output, index=False)
            output.seek(0)

            # Create HTTP response
            response = HttpResponse(output, content_type='text/csv')
            response['Content-Disposition'] = 'attachment; filename="import_results.csv"'
            
            if error_rows:
                messages.warning(request, f'{len(error_rows)} rows had errors. Check the output CSV for details.')
            else:
                messages.success(request, 'All rows were processed successfully.')

            return response

        except Exception as e:
            logger.error(f"Error processing CSV: {str(e)}")
            messages.error(request, f'An error occurred while processing the CSV: {str(e)}')
            return render(request, self.template_name)
        

    def process_dataframe(self, df, is_update, id_update, alternate):
        # Add import_status column
        df['import_status'] = ''

        # # Convert 'Yes'/'No' to boolean
        # bool_columns = [
        #     'is_principal', 'cfac_consulted', 'ag_work', 'child_5', 'plw', 'vul'
        # ] + [f'cfac_Q{i}' for i in range(1, 14)] + [f'A{i}' for i in range(1, 14)] + \
        #   ['cfac_exclusion', 'exclusion_1']
        
        # for col in bool_columns:
        #     if col in df.columns:
        #         df[col] = df[col].map({'Yes': True, 'No': False})
        
        
        df.rename(columns={'KEY': 'key'}, inplace=True)
        
        df['observation'] = df['observation'].map({1:True, 2:False})
        df['ag_work'] = df['ag_work'].map({1:True, 2:False})
        # Convert date columns
        date_columns = ['data_assess', 'SubmissionDate','start','end','today','date_return']
        for col in date_columns:
            if col in df.columns:
                df[col] = pd.to_datetime(df[col], errors='coerce', utc=True)
        # Sum columns A1 to A13 and store in a new column
        df['CP_Calculation'] = df[['A1', 'A2', 'A3', 'A4', 'A5', 'A6', 'A7', 
                                'A8', 'A9', 'A10', 'A11', 'A12', 'A13']].sum(axis=1)
        # if df['exclusion_1'] is 1 then df['vul'] = 'Excluded' else if df['CP_Calculation'] <6 then df['vul'] = 'No', else df['vul'] = 'Yes'
        
        # Apply the logic
        conditions = [
            (df['exclusion_1'] == 1),
            (df['CP_Calculation'] < 6)
        ]
        choices = ['Excluded', 'No']
        df['vul'] = np.select(conditions, choices, default='Yes')

        # Convert integer columns
        int_columns = ['ben_age', 'p_age', 'alter_age', 'child_5Num', 'c1age', 'c2age', 'c3age', 'c4age', 'c5age',
                       'pbw_num', 'CFAC_Calculation', 'CP_Calculation', 'difference']
        for col in int_columns:

base/templates/check_upload_excel.html
{% extends "main.html" %}
{% block content %}
<div class="content">
    <div class="block block-rounded">
        <div class="block-content block-content-full">
          <div class="py-3 text-center">
            <h1 class="h3 fw-extrabold mb-1">
              Check Data in System
            </h1>
            <h2 class="fs-sm fw-medium text-muted mb-0">
             This utility will help you to check if the data in your Excel file is already in the system or not.
            </h2>
          </div>
        </div>
      </div>
      <div class="block block-rounded">
        <div class="block-content block-content-full">
          <div class="py-3 text-center">
            <form class="row row-cols-lg-auto g-3 align-items-center" action="{% url 'check_keys_in_excel' %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="col-12">
                  <label class="visually-hidden" for="example-if-email">Excel File</label>
                  <input type="file" class="form-control" name="excel_file" accept=".xlsx">
                </div>
                
                <div>
                    <button class="btn btn-primary" type="submit">Import</button>
                </div>
            </form>
            
            
          </div>
          {% if file_url %}
            <a class="btn btn-primary" href="{% url 'data_quality:analyze_data' %}?file_url={{ file_url }}">Analyze Data</a>
            {% endif %}

        </div>
      </div>
        
</div>
{% endblock content %}

base/templates/login.html
<!doctype html>
<html lang="en">
  {% load static %}
{% include "head.html" %}
  <body>
   
    <div id="page-container" class="main-content-boxed">

      <!-- Main Container -->
      <main id="main-container">
        <!-- Page Content -->
        <div class="bg-gd-dusk">
          <div class="hero-static content content-full bg-body-extra-light">
            <!-- Header -->
            <div class="py-4 px-1 text-center mb-4">
              <a class="link-fx fw-bold" href="index.html">
                <i class="fa fa-fire"></i>
                <span class="fs-4 text-body-color">Targeting</span><span class="fs-4">App</span>
              </a>
              <h1 class="h3 fw-bold mt-5 mb-2">Welcome to Targeting App</h1>
              <h2 class="h5 fw-medium text-muted mb-0">Please sign in</h2>
            </div>
            <!-- END Header -->

            <!-- Sign In Form -->
            <div class="row justify-content-center px-1">
              <div class="col-sm-8 col-md-6 col-xl-4">
                <!-- jQuery Validation functionality is initialized with .js-validation-signin class in js/pages/op_auth_signin.min.js which was auto compiled from _js/pages/op_auth_signin.js -->
                <!-- For more examples you can check out https://github.com/jzaefferer/jquery-validation -->
                
                <form class="js-validation-signin" method="POST">
                    {% csrf_token %}
                  <div class="form-floating mb-4">
                    <input type="text" class="form-control" id="{{ form.username.id_for_label }}" name="{{ form.username.name }}" placeholder="Enter your password">
                    <label class="form-label" for="{{ form.username.id_for_label }}">{{ form.username.label }}</label>
                  </div>
                  <div class="form-floating mb-4">
                    <input type="password" class="form-control" id="{{ form.password.id_for_label }}" name="{{ form.password.name }}" placeholder="Enter your password">
                    <label class="form-label" for="{{ form.password.id_for_label }}">{{ form.password.label }}</label>
                  </div>
                  <div class="row g-sm mb-2">
                    <div class="col-12 mb-2">
                      <button type="submit" class="btn btn-lg btn-alt-primary w-100 py-2 fw-semibold">
                        Sign In
                      </button>
                    </div>
                    <div class="col-sm-12 mb-1">
                      <a class="btn btn-alt-secondary w-100" <a href="{% url 'register' %}">
                        New Account
                      </a>
                    </div>
                    
                  </div>
                </form>
              </div>
            </div>
            <!-- END Sign In Form -->
          </div>
        </div>
        <!-- END Page Content -->
      </main>
      <!-- END Main Container -->
    </div>
    <!-- END Page Container -->

    <!--
        Codebase JS

        Core libraries and functionality
        webpack is putting everything together at assets/_js/main/app.js
    -->
    {% include "javascript.html" %}
    

    <!-- Page JS Plugins -->
    
    <!-- Page JS Code -->
    {% block scripts %}
    <script src="{% static '/js/plugins/jquery-validation/jquery.validate.min.js' %}"></script>
    <script src="{% static '/js/pages/op_auth_signin.min.js' %}"></>
    {% endblock scripts %}
  </body>
</html>

base/templates/moda_actions.html
{% extends "main.html" %}
{% load static %}

{% block styles %}
<!-- Page JS Plugins CSS -->
<link rel="stylesheet" href="{% static '/js/plugins/sweetalert2/sweetalert2.min.css'%}">
{% endblock styles %}



{% block content %}
<div class="content">
    <div class="row">
      <div class="col-12">
        <!-- With Links -->
        <div class="block block-rounded">
          <div class="block-header block-header-default">
            <h3 class="block-title">{{ title }}</h3>
          </div>
          <div class="block-content">
            <div class="list-group push">
              <a class="list-group-item list-group-item-action d-flex justify-content-between align-items-center " href="#" data_url="{% url 'media_files:upload_province' %}">
                Upload Province to MoDa
              </a>
              <a class="list-group-item list-group-item-action d-flex justify-content-between align-items-center " href="#" data_url="{% url 'media_files:upload_district' %}">
                Upload District to MoDa
              </a>
              <a class="list-group-item list-group-item-action d-flex justify-content-between align-items-center " href="#" data_url="{% url 'media_files:upload_cfac' %}">
                Upload CFAC List to MoDa
              </a>
              <a class="list-group-item list-group-item-action d-flex justify-content-between align-items-center " href="#" data_url="{% url 'media_files:upload_villages' %}">
                Upload Village List to MoDa
              </a>
              <a class="list-group-item list-group-item-action d-flex justify-content-between align-items-center " href="#" data_url="{% url 'media_files:upload_cp' %}">
                Upload CP List to MoDa
              </a>
              <a class="list-group-item list-group-item-action d-flex justify-content-between align-items-center " href="#" data_url="{% url 'media_files:upload_tpm' %}">
                Upload TPM List to MoDa
              </a>
              
              <a class="list-group-item list-group-item-action d-flex justify-content-between align-items-center text-muted" href="javascript:void(0)" >
                Upload TPM Staff to MoDa
                <span class="badge rounded-pill bg-black-50">disabled</span>
              </a>
              <a class="list-group-item list-group-item-action d-flex justify-content-between align-items-center text-muted " href="javascript:void(0)" >
                Upload CP Staff List to MoDa
                <span class="badge rounded-pill bg-black-50">disabled</span>

              </a>
              <a class="list-group-item list-group-item-action d-flex justify-content-between align-items-center bg-gd-lake" href="#" data_url="{% url 'media_files:upload_sample' %}">
                Upload Sample to MoDa
              </a>
              <a class="list-group-item list-group-item-action d-flex justify-content-between align-items-center bg-gd-sea" href="#" data_url="{% url 'media_files:user_access' %}">
                Update MoDa User Access
              </a>
            </div>
          </div>
        </div>
        <!-- END With Links -->
      </div>
    </div>
  </div>

{% endblock content %}

{% block scripts %}
<!-- Page JS Plugins -->
<script src="{% static '/js/plugins/sweetalert2/sweetalert2.min.js' %}"></script>
<script>
  $(document).ready(function() {
      

      // Use event delegation to handle clicks on list-group-item elements
      $(document).on('click', '.list-group-item', function(e) {
          // Prevent default action
          e.preventDefault();
          
          // Check if the click event is triggered
          console.log("Item clicked!");

          // Get the URL from the data attribute
          let url = $(this).attr('data_url');
          console.log("URL: ", url);
          
          if (!url) {
              console.error("URL not found in the data_url attribute.");
              return;
          }
          
          // Show SweetAlert to indicate that the process has started
          Swal.fire({
              title: 'Processing...',
              text: 'Please wait while the process completes.',
              allowOutsideClick: false,
              didOpen: () => {
                  Swal.showLoading();
              }
          });

          // Fetch the URL and handle the response
          fetch(url)
              .then(response => {
                  console.log("Response received:", response);
                  if (!response.ok) {
                      throw new Error("Network response was not ok");
                  }
                  return response.json();
              })
              .then(data => {
                console.log(data)
                  // Close the loading alert
                  Swal.close();

                  // Show result based on the response status
                  if (data.success) {
                      Swal.fire({
                          title: 'Success',
                          text: data.success,
                          icon: 'success'
                      });
                  } else {
                      Swal.fire({
                          title: 'Error',
                          text: data.error,
                          icon: 'error'
                      });
                  }
              })
              .catch(error => {
                  // Close the loading alert
                  Swal.close();

                  // Show error alert if something goes wrong
                  Swal.fire({
                      title: 'Error',
                      text: 'An error occurred. Please try again.',
                      icon: 'error'
                  });
                  console.error('Error:', error);
              });
      });
  });
</script>


{% endblock scripts %}

base/templates/temp.html
{% extends "main.html" %}
{% block content %}
<div class="content">
    <h1> {{ title }} </h1>
  </div>

{% endblock content %}