base/urls.py
from django.urls import path
from . import views
from . import final_list_views

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('', views.home, name='home'),
    # path('dqa/', views.dqa, name='dqa'),
    path('import_data/', views.import_data, name='import_data'),
    path('error_check/', views.error_check, name='error_check'),
    path('final_list/', views.final_list, name='final_list'),
    path('final_list_report/', views.final_list_report, name='final_list_report'),
    path('reports/', views.reports, name='reports'),
    path('media_upload/', views.upload_media, name='media_upload'),
    path('upload_sample/', views.upload_sample_to_moda, name='upload_sample'),
    path('moda_user_mgt/', views.moda_user_mgt, name='moda_user_mgt'),
    path('import-csv/', views.CSVImportView.as_view(), name='csv_import'),
    path('import-tpm-csv/', views.TPMCSVImportView.as_view(), name='import_tpm_csv'),
    path('import-tpm-ee-csv/', views.TPMEEVImportView.as_view(), name='import_tpm_ee_csv'),
    path('drop_records/', views.CSVImportViewDropRecords.as_view(), name='drop_records'),
    
    path('sampling/', views.sampling, name='sampling'),
    path('est_sample/', views.CSVDataCountView.as_view(), name='est_sample'),
    path('generate_sample/', views.GenerateSampleView.as_view(), name='generate_sample'),
    path('approve_sample/', views.ApproveSampleView.as_view(), name='approve_sample'),
    path('sampling_report/', views.sampling_report, name='sampling_report'),
    path('sample_report/', views.SampleViewReport.as_view(), name='sample_report'),
    
    
    path('sampling_borderline/', views.sampling_borderline, name='sampling_borderline'),
    path('est_borderline_sample/', views.SampledLocations_bordeline.as_view(), name='est_borderline_sample'),
    # path('est_sample_borderline/', views.CSVDataCountViewBorderline.as_view(), name='est_sample_borderline'),
    path('gen_borderline_sample/', views.GenerateRandomSites.as_view(), name='gen_borderline_sample'),
    # path('approve_sample/', views.ApproveSampleView.as_view(), name='approve_sample'),
    
    path('custom_sampling_borderline/', views.custom_sampling_borderline, name='custom_sampling_borderline'),
    path('est_custom_borderline_sample/', views.SampledLocations_bordeline_custom.as_view(), name='est_custom_borderline_sample'),
    # path('est_sample_borderline/', views.CSVDataCountViewBorderline.as_view(), name='est_sample_borderline'),
    path('gen_custom_borderline_sample/', views.GenerateRandomSites_custom.as_view(), name='gen_custom_borderline_sample'),
    
    path('filal_list_locations/', views.SampledLocations.as_view(), name='filal_list_locations'),
    path('final_list_data_analysis/', views.FinalListDataAnalysis.as_view(), name='final_list_data_analysis'),
    path('final_list_data_analysis_report/', views.FinalListDataAnalysisReport.as_view(), name='final_list_data_analysis_report'),
    path('check_keys_in_excel/', views.check_keys_in_excel, name='check_keys_in_excel'),
    path('summary_view/', views.summary_view.as_view(), name='summary_view'),
    
    path('export/<str:model_name>/', views.export_model_to_excel, name='export_model_to_excel'),
    
    
    # test final views.
    path('final_list_test/', final_list_views.DataCountsGroupedView.as_view(), name='final_list_test'),
    # path('test_view_final_approval/', views.test_view_final_approval, name='final_list_test2'),
    path('test_view_final_approval/', views.FinalListApproval.as_view(), name='final_list_test3'),
    
    
    
]

data_quality/urls.py
from django.urls import path
from . import views

app_name = 'data_quality'  # replace 'data_quality' with your actual app name

urlpatterns = [
    path('', views.index, name='index'),
    path('create-df/', views.create_df, name='create-df'),
    path('import-data/', views.ImportDataView.as_view(), name='dqa'),
    path('dqa_analysis/', views.dqa_analysis, name='dqa_analysis'),
    path('excel_upload_view/', views.excel_upload_view, name='excel_import'),
    path('std_data_analysis/', views.std_data_analysis, name='analyze_data'),
    path('cfac_excel_upload_view/', views.cfac_excel_upload_view, name='cfac_excel_import'),
    path('cfac_village_list_prep/', views.process_excel_file, name='cfac_village_list_prep'),
    path('deduplicate_upload/', views.deduplicate_upload, name='deduplicate_upload'),
    path('deduplicate_export/', views.deduplicate_export, name='deduplicate_export'),
    path('compare_files/', views.compare_excel_documents, name='compare_files'),
    path('prepare_final_list/', views.prepare_final_list, name='prepare_final_list')
]

targeting/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
    path('data_quality/', include('data_quality.urls')),
    path('media_files/', include('media_files.urls')),
    
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

data_quality/models.py
from django.db import models

# Create your models here.

data_quality/forms.py
# comparer/forms.py

from django import forms

class ExcelCompareForm(forms.Form):
    first_document = forms.FileField(
        label='First Excel Document',
        required=True,
        help_text='Upload the first Excel file for comparison.',
         widget=forms.ClearableFileInput(attrs={
            'class': 'form-control',
            'accept': '.xlsx,.xls'
        })
    )
    second_document = forms.FileField(
        label='Second Excel Document',
        required=True,
        help_text='Upload the second Excel file to compare against the first.',
         widget=forms.ClearableFileInput(attrs={
            'class': 'form-control',
            'accept': '.xlsx,.xls'
        })
    )

data_quality/views.py
import pandas as pd
from django.http import HttpResponse, StreamingHttpResponse
from django.shortcuts import redirect, render
from django.views import View
from django.core.files.storage import default_storage, FileSystemStorage
from django.core.files.base import ContentFile
from dtale.views import startup
import io
import dtale.global_state as global_state
from django.conf import settings
from django.contrib import messages
import os
from datetime import datetime
from openpyxl import load_workbook
from .forms import ExcelCompareForm
from openpyxl.styles import PatternFill
from io import BytesIO
from openpyxl.utils.dataframe import dataframe_to_rows



from .data_quality_utils import (
    read_dataset,
    find_duplicate_id_number,
    find_duplicate_mobile_number,
    find_q5_a5_error,
    find_q6_a6_error,
    find_child_under_5_error,
    find_potential_hoh_duplicates,
    add_error_remarks,
    merge_error_subsets,
    produce_final_excel
)
from io import BytesIO
import xlsxwriter  # Ensure xlsxwriter is installed

global_state.set_app_settings(dict(enable_custom_filters=True, optimize_dataframe=True, ignore_duplicate=True,  lock_header_menu=True, main_title = 'Tageting DQA App'))


def index(request):
    return HttpResponse("""
        <h1>Django App with D-Tale</h1>
        <p><a href="/data_quality/create-df">Generate sample dataframe in D-Tale</a></p>
        <p><a href="/data_quality/import-data">Import CSV file to D-Tale</a></p>
    """)
    
def create_df(request):
    df = pd.DataFrame(dict(a=[1, 2, 3], b=[4, 5, 6]))
    instance = startup(data=df, ignore_duplicate=True)
    return redirect(f"/flask/dtale/main/{instance._data_id}")

# create data upload csv file and display in D-Tale

class ImportDataView(View):
    def get(self, request):
        return render(request, 'upload.html')
    
    def post(self, request):
        if 'file' not in request.FILES:
            return HttpResponse("No file uploaded", status=400)
        
        file = request.FILES['file']
        
        # Save the file temporarily
        path = default_storage.save('tmp/'+file.name, ContentFile(file.read()))
        
        try:
            # Read the CSV file
            with default_storage.open(path) as f:
                df = pd.read_csv(io.StringIO(f.read().decode('utf-8')))
            
            # Start D-Tale with the imported data
            instance = startup(data=df)
            # print(instance.)
            url = f"/flask/dtale/main/{instance._data_id}"
            print(url)
            # Redirect to D-Tale
            return render(request, 'dtale.html', context={'url': url})
        except Exception as e:
            return HttpResponse(f"Error processing file: {str(e)}", status=400)
        finally:
            # Clean up the temporary file
            default_storage.delete(path)
            
def dqa_analysis(request):
    return render(request, 'dtale.html', context={'url': request.GET.get('url')})

def excel_upload_view(request):
    if request.method == 'POST':
        if 'excel_file' not in request.FILES:
            messages.error(request, 'No file selected')
            return redirect('upload_excel')
        
        excel_dqa_file = request.FILES['excel_file']
        
        # Check if the uploaded file is an Excel (.xlsx) file
        if not excel_dqa_file.name.endswith('.xlsx'):
            messages.error(request, 'Please upload a valid .xlsx file')
            return redirect('upload_excel')

        # Generate a unique filename by appending the current timestamp
        original_filename = excel_dqa_file.name
        file_extension = os.path.splitext(original_filename)[1]  # Get the file extension
        timestamp = datetime.now().strftime("%Y%m%d%H%M%S")  # Get the current timestamp
        unique_filename = f"{os.path.splitext(original_filename)[0]}_{timestamp}{file_extension}"

        # Define the folder to save the file in
        fs = FileSystemStorage(location=os.path.join(settings.MEDIA_ROOT, 'excel_files'))
        
        # Save the file with the unique filename
        filename = fs.save(unique_filename, excel_dqa_file)
        file_url = fs.url(filename)

        # Display success message
        messages.success(request, f'File uploaded successfully: {file_url}')
        
        context = {'file_url': file_url}
        return render(request, 'upload_excel.html', context=context)
        
        
    # Render the file upload form if the request method is GET
    return render(request, 'upload_excel.html')

def std_data_analysis1(request):
    file_url = request.GET.get('file_url')
    
    if file_url:
        # Extract the filename from the file URL
        file_name = os.path.basename(file_url)
        
        # Construct the full file path based on MEDIA_ROOT
        file_path = os.path.join(settings.MEDIA_ROOT, 'excel_files', file_name)
        print(file_path)
        
        if not os.path.exists(file_path):
            return HttpResponse("File not found", status=404)

        try:
            # Use a generator to stream the data in chunks manually
            def excel_data_generator(file_path):
                wb = load_workbook(file_path, read_only=True)
                ws = wb.active
                
                # Read rows in chunks manually (adjust as needed)
                chunk_size = 1000
                rows = ws.iter_rows(values_only=True)
                chunk = []
                for idx, row in enumerate(rows):
                    chunk.append(row)
                    if (idx + 1) % chunk_size == 0:
                        yield pd.DataFrame(chunk).to_json(orient='records')
                        chunk = []
                
                # Yield the remaining rows if any
                if chunk:
                    yield pd.DataFrame(chunk).to_json(orient='records')

            # Create a StreamingHttpResponse for large data
            response = StreamingHttpResponse(excel_data_generator(file_path), content_type='application/json')
            response['Content-Disposition'] = f'attachment; filename="{file_name}"'

            return response

        except Exception as e:
            return HttpResponse(f"Error processing the file: {str(e)}", status=500)
    else:
        return HttpResponse("No file URL provided", status=400)


def calculate_time_difference(df, start_col='start', end_col='end'):
    """
    Calculate the difference in minutes between start_time and end_time and return a new DataFrame with the result.

    :param df: pandas DataFrame containing the start and end time columns
    :param start_col: Name of the start time column (default is 'start_time')
    :param end_col: Name of the end time column (default is 'end_time')
    :return: A new DataFrame with the original data and an additional column 'time_difference_minutes'
    """

    # Create a copy of the DataFrame to avoid modifying the original
    df_copy = df.copy()

    # Ensure that start_time and end_time are in datetime format
    df_copy[start_col] = pd.to_datetime(df_copy[start_col], errors='coerce')
    df_copy[end_col] = pd.to_datetime(df_copy[end_col], errors='coerce')

    # Calculate the time difference in minutes
    df_copy['time_difference_minutes'] = (df_copy[end_col] - df_copy[start_col]).dt.total_seconds() / 60

    # Handling potential missing or invalid values by replacing them with NaN or a default value (e.g., 0)
    df_copy['time_difference_minutes'] = df_copy['time_difference_minutes'].fillna(0)

    return df_copy


def std_data_analysis(request):
    file_url = request.GET.get('file_url')
    
    if file_url:
        # Extract the filename from the file URL
        file_name = os.path.basename(file_url)
        
        # Construct the full file path based on MEDIA_ROOT
        file_path = os.path.join(settings.MEDIA_ROOT, 'excel_files', file_name)
        
        df = read_dataset(file_path)

        # Section Two: Duplicate id_number
        dup_id_num = find_duplicate_id_number(df)
        dup_id_num = add_error_remarks(
            dup_id_num,
            'Duplicate ID Number:',
            'Duplicate ID number identified based on paper or electronic tazkira (column name id_number). Please review the entries and determine if the data is valid, or if the duplicate records should be removed.'
        )

        # Section Three: Duplicate Mobile Number
        dup_mob_rows = find_duplicate_mobile_number(df)
        dup_mob_rows = add_error_remarks(
            dup_mob_rows,
            'Duplicate Mobile Number',
            'Duplicate mobile number detected (column name mob). Please review and determine whether the mobile numbers need correction or if any duplicates should be removed.'
        )

        # Section Four: Q5/A5 error
        a5_error = find_q5_a5_error(df)
        a5_error = add_error_remarks(
            a5_error,
            'Vulnerability Q5 Error: (The head of the household has a disability.)',
            'Inconsistency found in Vulnerability Question 5 (column A5). The household is marked as disabled (column HH_head has value 3), but Question 5 indicates "No". Please review the data and correct this discrepancy.'
        )

        # Section Five: Q6/A6 Error
        a6_error = find_q6_a6_error(df)
        a6_error = add_error_remarks(
            a6_error,
            'Vulnerability Q6 Error: (The household has more than 3 children under the age of 5.)',
            'Vulnerability Question 6 has a potential issue: either Q6 (column name A6 is marked 1) is marked "Yes" but there are fewer (in column child_5Num) than 4 children under 5, or Q6 is marked "No" but there are more than 3 children under 5. Please verify the data and make necessary corrections.'
        )

        # Section Six: Children Under 5 Error
        child_5_error = find_child_under_5_error(df)
        child_5_error = add_error_remarks(
            child_5_error,

data_quality/templates/deduplicate.html
{% extends "main.html" %}
{% block content %}
<div class="content">
    <div class="block block-rounded">
        <div class="block-content block-content-full">
          <div class="py-3 text-center">
            <h1 class="h3 fw-extrabold mb-1">
              De-duplicataion of Data
            </h1>
            
          </div>
        </div>
      </div>
      <div class="block block-rounded">
        <div class="block-content block-content-full">
          <div class="py-3 text-center">
            <form class="row row-cols-lg-auto g-3 align-items-center" action="{% url 'data_quality:deduplicate_upload' %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="col-12">
                  <label class="visually-hidden" for="example-if-email">Excel File</label>
                  <input type="file" class="form-control" name="excel_file" accept=".xlsx">
                </div>
                
                <div>
                    <button class="btn btn-primary" type="submit">Import</button>
                </div>
            </form>
            
            
          </div>
          {% if file_url %}
            <a class="btn btn-primary" href="{% url 'data_quality:deduplicate_export' %}?file_url={{ file_url }}">Deduplicate</a>
            {% endif %}

        </div>
      </div>
      <h1 class="h3 fw-extrabold mb-1">
        Important Notes:
      </h1>
      <h2 class="fs-sm fw-medium text-muted mb-0">
        It will de-duplicate the data based on all the columns
       </h2>
       
        
</div>
{% endblock content %}

data_quality/templates/dtale.html
{% extends "main.html" %}
{% block content %}

        <div class="container-fluid">
            <iframe src="{{ url }}" width="100%" height="900px" frameborder="0"></iframe>
        </div>
{% endblock content %}

data_quality/templates/upload.html
{% extends "main.html" %}
{% block content %}
<div class="content">
    <div class="block block-rounded">
        <div class="block-content block-content-full">
          <div class="py-3 text-center">
            <h1 class="h3 fw-extrabold mb-1">
              Data Quality Asessment
            </h1>
            <h2 class="fs-sm fw-medium text-muted mb-0">
             Please import data in CSV and check for data quality
            </h2>
          </div>
        </div>
      </div>
      <div class="block block-rounded">
        <div class="block-content block-content-full">
          <div class="py-3 text-center">
            <form class="row row-cols-lg-auto g-3 align-items-center" action="{% url 'data_quality:dqa' %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="col-12">
                  <label class="visually-hidden" for="example-if-email">Email</label>
                  <input type="file" class="form-control" name="file" accept=".csv">
                </div>
                
                <div>
                    <button class="btn btn-primary" type="submit">Import</button>
                </div>
            </form>
            
          </div>
        </div>
      </div>
        
</div>
{% endblock content %}

data_quality/templates/upload_c.html
{% extends "main.html" %}
{% block content %}
<div class="content">
    <div class="block block-rounded">
        <div class="block-content block-content-full">
          <div class="py-3 text-center">
            <h1 class="h3 fw-extrabold mb-1">
                Compare Two Excel Documents
            </h1>
            <h2 class="fs-sm fw-medium text-muted mb-0">
             Compare documents to find the differences between them.
            </h2>
          </div>
        </div>
      </div>
      <div class="block block-rounded">
        <div class="block-content block-content-full">
          <div class="py-3 text-left">
            <div class="container">
                
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <input class="btn btn-primary" type="submit"  value="Compare">
                </form>
            </div>
           
            
          </div>
        </div>
      </div>
        
</div>
{% endblock content %}

data_quality/templates/upload_excel.html
{% extends "main.html" %}
{% block content %}
<div class="content">
    <div class="block block-rounded">
        <div class="block-content block-content-full">
          <div class="py-3 text-center">
            <h1 class="h3 fw-extrabold mb-1">
              Data Quality Asessment
            </h1>
            <h2 class="fs-sm fw-medium text-muted mb-0">
             Please import data in CSV and check for data quality
            </h2>
          </div>
        </div>
      </div>
      <div class="block block-rounded">
        <div class="block-content block-content-full">
          <div class="py-3 text-center">
            <form class="row row-cols-lg-auto g-3 align-items-center" action="{% url 'data_quality:excel_import' %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="col-12">
                  <label class="visually-hidden" for="example-if-email">Excel File</label>
                  <input type="file" class="form-control" name="excel_file" accept=".xlsx">
                </div>
                
                <div>
                    <button class="btn btn-primary" type="submit">Import</button>
                </div>
            </form>
            
            
          </div>
          {% if file_url %}
            <a class="btn btn-primary" href="{% url 'data_quality:analyze_data' %}?file_url={{ file_url }}">Analyze Data</a>
            {% endif %}

        </div>
      </div>
        
</div>
{% endblock content %}

data_quality/templates/upload_excel_cfac.html
{% extends "main.html" %}
{% block content %}
<div class="content">
    <div class="block block-rounded">
        <div class="block-content block-content-full">
          <div class="py-3 text-center">
            <h1 class="h3 fw-extrabold mb-1">
              CFAC & Village Data List Preparation
            </h1>
            
          </div>
        </div>
      </div>
      <div class="block block-rounded">
        <div class="block-content block-content-full">
          <div class="py-3 text-center">
            <form class="row row-cols-lg-auto g-3 align-items-center" action="{% url 'data_quality:cfac_excel_import' %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="col-12">
                  <label class="visually-hidden" for="example-if-email">Excel File</label>
                  <input type="file" class="form-control" name="excel_file" accept=".xlsx">
                </div>
                
                <div>
                    <button class="btn btn-primary" type="submit">Import</button>
                </div>
            </form>
            
            
          </div>
          {% if file_url %}
            <a class="btn btn-primary" href="{% url 'data_quality:cfac_village_list_prep' %}?file_url={{ file_url }}">Prepare CFAC and Village Data</a>
            {% endif %}

        </div>
      </div>
      <h1 class="h3 fw-extrabold mb-1">
        Important Notes:
      </h1>
      <h2 class="fs-sm fw-medium text-muted mb-0">
        Please import data in Excel with only one sheet and it should have these 
        ['AO', 'Area', 'Province', 'District', 'Village', 'Nahia', 'CFAC Name','CFAC FP 1', 'FP1 Number', 'CFAC FP2', 'FP2 Number', 'Remarks'] columns.
       </h2>
       <h2 class="fs-sm fw-medium text-muted mb-0">
         Area Office should be in short form
       </h2>
       <h2 class="fs-sm fw-medium text-muted mb-0">
         Province and District should be consistent with the data in the database
       </h2>
        
</div>
{% endblock content %}

data_quality/templates/upload_finalList.html
{% extends "main.html" %}
{% block content %}
<div class="content">
    <div class="block block-rounded">
        <div class="block-content block-content-full">
          <div class="py-3 text-center">
            <h1 class="h3 fw-extrabold mb-1">
                Compare Two Excel Documents
            </h1>
            <h2 class="fs-sm fw-medium text-muted mb-0">
             Compare documents to find the differences between them.
            </h2>
          </div>
        </div>
      </div>
      <div class="block block-rounded">
        <div class="block-content block-content-full">
          <div class="py-3 text-left">
            <div class="container">
                
              <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <label for="excel_file">Select Excel file:</label>
                <input type="file" name="excel_file" id="excel_file" class="form-control" required><br><br>
            
                {% comment %} <label for="password1">Password to open the file:</label>
                <input type="password" name="password1" id="password1" class="form-control"  required><br><br>
            
                <label for="password2">Password to modify the file:</label>
                <input type="password" name="password2" id="password2" class="form-control"  required><br><br>
             {% endcomment %}
                <button class="btn btn-primary btn-block" type="submit">Upload and Process</button>
            </form>
            
            </div>
           
            
          </div>
        </div>
      </div>
        
</div>
{% endblock content %}